[package]
name = "rs-sandbox"
version = "0.1.0"
edition = "2021"
authors = ["Keyno63 <kofujiw@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1"
